<?php

            return array(
                '00'=>array('vif'=>'Energy mWh')
                ,'01'=>array('vif'=>'Energy 10<sup>-2</sup> Wh')
                ,'02'=>array('vif'=>'Energy 10<sup>-1</sup> Wh')
                ,'03'=>array('vif'=>'Energy Wh')
                ,'04'=>array('vif'=>'Energy 10<sup>1</sup> Wh')
                ,'05'=>array('vif'=>'Energy 10<sup>2</sup> Wh')
                ,'06'=>array('vif'=>'Energy kWh')
                ,'07'=>array('vif'=>'Energy 10<sup>4</sup> Wh')
                ,'08'=>array('vif'=>'Energy J')
                ,'09'=>array('vif'=>'Energy 10<sup>1</sup> J')
                ,'0a'=>array('vif'=>'Energy 10<sup>2</sup> J')
                ,'0b'=>array('vif'=>'Energy kJ')
                ,'0c'=>array('vif'=>'Energy 10<sup>4</sup> J')
                ,'0d'=>array('vif'=>'Energy 10<sup>5</sup> J')
                ,'0e'=>array('vif'=>'Energy MJ')
                ,'0f'=>array('vif'=>'Energy 10<sup>7</sup> J')
                ,'10'=>array('vif'=>'Volume cm<sup>3</sup>')
                ,'11'=>array('vif'=>'Volume 10<sup>-5</sup> m<sup>3</sup>')
                ,'12'=>array('vif'=>'Volume 10<sup>-4</sup> m<sup>3</sup>')
                ,'13'=>array('vif'=>'Volume l')
                ,'14'=>array('vif'=>'Volume 10<sup>-2</sup> m<sup>3</sup>')
                ,'15'=>array('vif'=>'Volume 10<sup>-1</sup> m<sup>3</sup>')
                ,'16'=>array('vif'=>'Volume m<sup>3</sup>')
                ,'17'=>array('vif'=>'Volume 10<sup>1</sup> m<sup>3</sup>')
                ,'18'=>array('vif'=>'Mass g')
                ,'19'=>array('vif'=>'Mass 10<sup>-2</sup> kg')
                ,'1a'=>array('vif'=>'Mass 10<sup>-1</sup> kg')
                ,'1b'=>array('vif'=>'Mass kg')
                ,'1c'=>array('vif'=>'Mass 10<sup>1</sup> kg')
                ,'1d'=>array('vif'=>'Mass 10<sup>2</sup> kg')
                ,'1e'=>array('vif'=>'Mass t')
                ,'1f'=>array('vif'=>'Mass 10<sup>4</sup> kg')
                ,'20'=>array('vif'=>'On time seconds')
                ,'21'=>array('vif'=>'On time minutes')
                ,'22'=>array('vif'=>'On time hours')
                ,'23'=>array('vif'=>'On time days')
                ,'24'=>array('vif'=>'Operating time seconds')
                ,'25'=>array('vif'=>'Operating time minutes')
                ,'26'=>array('vif'=>'Operating time hours')
                ,'27'=>array('vif'=>'Operating time days')
                ,'28'=>array('vif'=>'Power mW')
                ,'29'=>array('vif'=>'Power 10<sup>-2</sup> W')
                ,'2a'=>array('vif'=>'Power 10<sup>-1</sup> W')
                ,'2b'=>array('vif'=>'Power W')
                ,'2c'=>array('vif'=>'Power 10<sup>1</sup> W')
                ,'2d'=>array('vif'=>'Power 10<sup>2</sup> W')
                ,'2e'=>array('vif'=>'Power kW')
                ,'2f'=>array('vif'=>'Power 10<sup>4</sup> W')
                ,'30'=>array('vif'=>'Power J/h')
                ,'31'=>array('vif'=>'Power 10<sup>1</sup> J/h')
                ,'32'=>array('vif'=>'Power 10<sup>2</sup> J/h')
                ,'33'=>array('vif'=>'Power kJ/h')
                ,'34'=>array('vif'=>'Power 10<sup>4</sup> J/h')
                ,'35'=>array('vif'=>'Power 10<sup>5</sup> J/h')
                ,'36'=>array('vif'=>'Power MJ/h')
                ,'37'=>array('vif'=>'Power 10<sup>7</sup> J/h')
                ,'38'=>array('vif'=>'Volume flow cm<sup>3</sup>/h')
                ,'39'=>array('vif'=>'Volume flow 10<sup>-5</sup> m<sup>3</sup>/h')
                ,'3a'=>array('vif'=>'Volume flow 10<sup>-4</sup> m<sup>3</sup>/h')
                ,'3b'=>array('vif'=>'Volume flow l/h')
                ,'3c'=>array('vif'=>'Volume flow 10<sup>-2</sup> m<sup>3</sup>/h')
                ,'3d'=>array('vif'=>'Volume flow 10<sup>-1</sup> m<sup>3</sup>/h')
                ,'3e'=>array('vif'=>'Volume flow m<sup>3</sup>/h')
                ,'3f'=>array('vif'=>'Volume flow 10<sup>1</sup> m<sup>3</sup>/h')
                ,'40'=>array('vif'=>'Volume flow ext. 10<sup>-7</sup> m<sup>3</sup>/min')
                ,'41'=>array('vif'=>'Volume flow ext. cm<sup>3</sup>/min')
                ,'42'=>array('vif'=>'Volume flow ext. 10<sup>-5</sup> m<sup>3</sup>/min')
                ,'43'=>array('vif'=>'Volume flow ext. 10<sup>-4</sup> m<sup>3</sup>/min')
                ,'44'=>array('vif'=>'Volume flow ext. l/min')
                ,'45'=>array('vif'=>'Volume flow ext. 10<sup>-2</sup> m<sup>3</sup>/min')
                ,'46'=>array('vif'=>'Volume flow ext. 10<sup>-1</sup> m<sup>3</sup>/min')
                ,'47'=>array('vif'=>'Volume flow ext. m<sup>3</sup>/min')
                ,'48'=>array('vif'=>'Volume flow ext. mm<sup>3</sup>/s')
                ,'49'=>array('vif'=>'Volume flow ext. 10<sup>-8</sup> m<sup>3</sup>/s')
                ,'4a'=>array('vif'=>'Volume flow ext. 10<sup>-7</sup> m<sup>3</sup>/s')
                ,'4b'=>array('vif'=>'Volume flow ext. cm<sup>3</sup>/s')
                ,'4c'=>array('vif'=>'Volume flow ext. 10<sup>-5</sup> m<sup>3</sup>/s')
                ,'4d'=>array('vif'=>'Volume flow ext. 10<sup>-4</sup> m<sup>3</sup>/s')
                ,'4e'=>array('vif'=>'Volume flow ext. l/s')
                ,'4f'=>array('vif'=>'Volume flow ext. 10<sup>-2</sup> m<sup>3</sup>/s')
                ,'50'=>array('vif'=>'Mass g/h')
                ,'51'=>array('vif'=>'Mass 10<sup>-2</sup> kg/h')
                ,'52'=>array('vif'=>'Mass 10<sup>-1</sup> kg/h')
                ,'53'=>array('vif'=>'Mass kg/h')
                ,'54'=>array('vif'=>'Mass 10<sup>1</sup> kg/h')
                ,'55'=>array('vif'=>'Mass 10<sup>2</sup> kg/h')
                ,'56'=>array('vif'=>'Mass t/h')
                ,'57'=>array('vif'=>'Mass 10<sup>4</sup> kg/h')
                ,'58'=>array('vif'=>'Flow temperature 10<sup>-3</sup> °c')
                ,'59'=>array('vif'=>'Flow temperature 10<sup>-2</sup> °c')
                ,'5a'=>array('vif'=>'Flow temperature 10<sup>-1</sup> °c')
                ,'5b'=>array('vif'=>'Flow temperature °c')
                ,'5c'=>array('vif'=>'Return temperature 10<sup>-3</sup> °c')
                ,'5d'=>array('vif'=>'Return temperature 10<sup>-2</sup> °c')
                ,'5e'=>array('vif'=>'Return temperature 10<sup>-1</sup> °c')
                ,'5f'=>array('vif'=>'Return temperature °c')
                ,'60'=>array('vif'=>'Temperature difference mK')
                ,'61'=>array('vif'=>'Temperature difference 10<sup>-2</sup> K')
                ,'62'=>array('vif'=>'Temperature difference 10<sup>-1</sup> K')
                ,'63'=>array('vif'=>'Temperature difference K')
                ,'64'=>array('vif'=>'External temperature 10<sup>-3</sup> °c')
                ,'65'=>array('vif'=>'External temperature 10<sup>-2</sup> °c')
                ,'66'=>array('vif'=>'External temperature 10<sup>-1</sup> °c')
                ,'67'=>array('vif'=>'External temperature °c')
                ,'68'=>array('vif'=>'Pressure mbar')
                ,'69'=>array('vif'=>'Pressure 10<sup>-2</sup> bar')
                ,'6a'=>array('vif'=>'Pressure 10⁻1 bar')
                ,'6b'=>array('vif'=>'Pressure bar')
                ,'6c'=>array('vif'=>'Date type G')
                ,'6e'=>array('vif'=>'Units for H.C.A.')
                ,'6f'=>array('vif'=>'Reserved')
                ,'70'=>array('vif'=>'Averaging duration seconds')
                ,'71'=>array('vif'=>'Averaging duration minutes')
                ,'72'=>array('vif'=>'Averaging duration hours')
                ,'73'=>array('vif'=>'Averaging duration days')
                ,'74'=>array('vif'=>'Actuality duration seconds','vife1'=>'Remaining Battery life time (days)')
                ,'75'=>array('vif'=>'Actuality duration minutes')
                ,'76'=>array('vif'=>'Actuality duration hours')
                ,'77'=>array('vif'=>'Actuality duration days')
                ,'78'=>array('vif'=>'Fabrication no')
                ,'79'=>array('vif'=>'Enhanced identification')
                ,'80'=>array('vif'=>'Address')
                ,'7c'=>array('vif'=>'VIF in following string (length in first byte)')
                ,'7e'=>array('vif'=>'Any VIf')
                ,'7f'=>array('vif'=>'Manufacturer specific')
            );
